"""Run a training job end to end on Kaggle's free GPU, without anyone
clicking anything.

Colab has no API -- it is browser-only by design -- but Kaggle exposes
the same class of free hardware (T4) through a real one, so the whole
cycle can be scripted: push the data and training code as a dataset,
submit a GPU kernel that runs it, poll, pull the checkpoint back.

    python training/kaggle_train.py --script training/train_dual_encoder.py \
        --data data/seed_examples.jsonl data/phishing_core_train.jsonl \
        --out models/sys1-from-kaggle

Credentials come from .env (KAGGLE_USERNAME + KAGGLE_API_TOKEN), same
pattern as the HF token. Nothing is printed that shouldn't be.
"""
from __future__ import annotations

import os
import sys

# The kaggle client writes kernel logs using the platform default codec,
# and those logs contain progress-bar glyphs. On Windows that raises
# UnicodeEncodeError part-way through the download, which is how a
# finished training run ends up looking like a hung one.
#
# Setting PYTHONUTF8 here is not enough on its own: the interpreter reads
# it at startup, so an in-process assignment changes nothing. Re-exec
# once with it set, guarded against looping.
if (
    sys.stdout.encoding
    and sys.stdout.encoding.lower().replace("-", "") != "utf8"
    and not os.environ.get("_SYS1_UTF8_REEXEC")
):
    # subprocess, not os.execv: on Windows execv re-parses its arguments
    # and mangles any path containing a space, which this project's own
    # checkout does.
    import subprocess

    env = {**os.environ, "PYTHONUTF8": "1", "_SYS1_UTF8_REEXEC": "1"}
    sys.exit(subprocess.run([sys.executable, *sys.argv], env=env).returncode)

import argparse
import json
import os
import shutil
import time
from pathlib import Path


def load_credentials(env_path: Path = Path(".env")) -> str:
    """Returns the Kaggle username, and puts the key where the client
    expects it. Must run before importing kaggle -- the client reads
    credentials at import time."""
    if env_path.is_file():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                os.environ.setdefault(key.strip(), value.strip())
    if "KAGGLE_KEY" not in os.environ and "KAGGLE_API_TOKEN" in os.environ:
        os.environ["KAGGLE_KEY"] = os.environ["KAGGLE_API_TOKEN"]
    username = os.environ.get("KAGGLE_USERNAME")
    if not username or not os.environ.get("KAGGLE_KEY"):
        raise RuntimeError("KAGGLE_USERNAME and KAGGLE_API_TOKEN must be set (see .env)")
    return username


KERNEL_TEMPLATE = '''"""Generated by training/kaggle_train.py -- runs our own trainer unchanged."""
import subprocess
import sys

import os

OUT_DIR = "/kaggle/working/model"

# Don't assume where Kaggle mounts a dataset -- the slug-to-path mapping
# is its own business and guessing it wrong fails as a bare "no such
# file". Find our files, and show the tree if we can't.
def find(filename):
    for root, _dirs, files in os.walk("/kaggle/input"):
        if filename in files:
            return os.path.join(root, filename)
    return None

script_path = find("{script_name}")
if script_path is None:
    print("could not find {script_name}; /kaggle/input contains:", flush=True)
    for root, _dirs, files in os.walk("/kaggle/input"):
        print(" ", root, files, flush=True)
    sys.exit(2)

DATA_DIR = os.path.dirname(script_path)
print("resolved data dir:", DATA_DIR, flush=True)
print("contents:", sorted(os.listdir(DATA_DIR)), flush=True)

cmd = [
    sys.executable,
    script_path,
    {data_args}
    "--out-dir", OUT_DIR,
    {extra_args}
]
print("running:", " ".join(cmd), flush=True)
result = subprocess.run(cmd)
sys.exit(result.returncode)
'''


def build_payload(staging: Path, script: Path, data_files: list[Path]) -> None:
    """Dataset payload holds both the data and our training code, so the
    kernel runs the exact same script we run locally rather than a
    re-implementation that can drift."""
    staging.mkdir(parents=True, exist_ok=True)
    shutil.copy(script, staging / script.name)
    for f in data_files:
        shutil.copy(f, staging / f.name)


def main() -> None:
    username = load_credentials()
    from kaggle.api.kaggle_api_extended import KaggleApi

    parser = argparse.ArgumentParser()
    parser.add_argument("--script", type=Path, required=True)
    parser.add_argument("--data", type=Path, nargs="+", required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--slug", default="sys1-train")
    # One quoted string rather than nargs="*": argparse refuses to treat
    # values beginning with "-" as positional values, so
    # `--extra-args --backbone X` fails as an unrecognised option.
    parser.add_argument("--extra-args", default="",
                        help='extra flags for the training script, e.g. "--backbone X --batch-size 32"')
    parser.add_argument("--poll-seconds", type=int, default=30)
    parser.add_argument("--timeout-minutes", type=int, default=90)
    args = parser.parse_args()

    api = KaggleApi()
    api.authenticate()

    dataset_slug = f"{args.slug}-data"
    dataset_id = f"{username}/{dataset_slug}"
    kernel_id = f"{username}/{args.slug}"

    staging = Path(".kaggle_staging")
    shutil.rmtree(staging, ignore_errors=True)
    data_dir = staging / "data"
    build_payload(data_dir, args.script, args.data)

    (data_dir / "dataset-metadata.json").write_text(
        json.dumps({"title": dataset_slug, "id": dataset_id, "licenses": [{"name": "CC0-1.0"}]}),
        encoding="utf-8",
    )

    print(f"uploading data + trainer to {dataset_id} ...", flush=True)
    try:
        api.dataset_create_new(str(data_dir), public=False, quiet=True, dir_mode="skip")
    except Exception as exc:  # already exists -> push a new version
        if "already" not in str(exc).lower():
            raise
        api.dataset_create_version(str(data_dir), version_notes="update", quiet=True, dir_mode="skip")
    # A fixed sleep here is a guess, and guessing wrong is silent: the
    # kernel pins whatever dataset version exists at push time, so pushing
    # early means it runs against stale files and fails with a confusing
    # "no such file". Poll until every file we uploaded is actually listed.
    expected = {args.script.name} | {f.name for f in args.data}
    print("waiting for the dataset to finish processing ...", flush=True)
    for attempt in range(40):
        time.sleep(15)
        try:
            listed = {f.name for f in api.dataset_list_files(dataset_id).files}
        except Exception:
            continue
        missing = expected - listed
        if not missing:
            print(f"  dataset ready ({len(listed)} files)", flush=True)
            break
        print(f"  still processing, missing {sorted(missing)}", flush=True)
    else:
        raise TimeoutError(f"dataset {dataset_id} never finished processing")

    kernel_dir = staging / "kernel"
    kernel_dir.mkdir(parents=True, exist_ok=True)
    data_args = "".join('f"{DATA_DIR}/' + f.name + '", ' for f in args.data)
    extra = "".join(f'"{a}", ' for a in args.extra_args.split())
    (kernel_dir / "script.py").write_text(
        KERNEL_TEMPLATE.format(
            dataset_slug=dataset_slug,
            script_name=args.script.name,
            data_args=data_args,
            extra_args=extra,
        ),
        encoding="utf-8",
    )
    (kernel_dir / "kernel-metadata.json").write_text(
        json.dumps(
            {
                "id": kernel_id,
                "title": args.slug,
                "code_file": "script.py",
                "language": "python",
                "kernel_type": "script",
                "is_private": True,
                "enable_gpu": True,
                "enable_internet": True,
                "dataset_sources": [dataset_id],
                "competition_sources": [],
                "kernel_sources": [],
            }
        ),
        encoding="utf-8",
    )

    print(f"pushing kernel {kernel_id} ...", flush=True)
    api.kernels_push(str(kernel_dir))

    deadline = time.time() + args.timeout_minutes * 60
    last = None
    while time.time() < deadline:
        time.sleep(args.poll_seconds)
        try:
            status = api.kernels_status(kernel_id)
        except Exception as exc:
            print(f"  (status check failed, retrying: {exc})", flush=True)
            continue
        state = status.get("status") if isinstance(status, dict) else getattr(status, "status", None)
        if state != last:
            print(f"  status: {state}", flush=True)
            last = state
        if str(state).lower() in {"complete", "error", "cancelacknowledged"}:
            break
    else:
        raise TimeoutError(f"kernel still running after {args.timeout_minutes} minutes")

    if str(last).lower() == "error":
        print("\nkernel failed -- pulling its log:", flush=True)
        args.out.mkdir(parents=True, exist_ok=True)
        api.kernels_output(kernel_id, path=str(args.out), quiet=True)
        for log in args.out.glob("*.log"):
            print(log.read_text(encoding="utf-8", errors="replace")[-4000:])
        raise SystemExit(1)

    args.out.mkdir(parents=True, exist_ok=True)
    print(f"downloading output to {args.out} ...", flush=True)
    api.kernels_output(kernel_id, path=str(args.out), quiet=True)
    print(f"done. contents: {sorted(p.name for p in args.out.iterdir())}")


if __name__ == "__main__":
    main()
